function multiphases = ReadTFSOrientationData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MULTIPHASES = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  MULTIPHASES = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  multiphases = importfile("D:\ApreoTruePixData\2025-03-31T14_04_15_Tianbi_Ebru_SiC\2025-03-31T14_23_02\results\multiphases.idx", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Apr-2025 08:54:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["y", "x", "Phi1", "PHI", "Phi2", "MisFit", "MAD", "PhaseID", "Q0", "Q1", "Q2", "Q3"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
multiphases = readtable(filename, opts);

end