%% Map segmentation scripts
% Each section does its own work and the script shall not be ran as a
% whole.

%% Read metadata
pname1 = "D:\RKD_Data\2023-11-16T12_36_34_WSe2_orig\2023-11-16T13_36_03";
fname1 = "site.json";
TFSJson = ReadTFSJson(pname1, fname1);

%% Get region indices
% reads in the result mat file, which is generated by the PCA/MSA routine.

load("Demo_Tianbi_16bin_PCA_.mat"); 

numPoints = TFSJson.Info.TotalNumberOfPoints;
width = TFSJson.Info.Width;
height = TFSJson.Info.Height;

%% Now produce the filtered MSA assignment map
cmapdouble = [
    0,0,0;
55,126,184;
77,175,74;
228,26,28;
% 152,78,163;
% 255,127,0;
] ./ 255;

z2 = find(VMOutput.PCA_VM_num == 2);
z4 = find(VMOutput.PCA_VM_num == 4);
z10 = find(VMOutput.PCA_VM_num == 10);

allz = [z2; z4; z10];

emptyMap = zeros(height, width);
emptyMap(z2) = 1;
emptyMap(z4) = 2;
emptyMap(z10) = 3;

figure; imagesc(emptyMap); axis image; hold on; axis off;
colormap(cmap(1:4,:))
cb = colorbar;
cb.TickLabels = [];
cb.Ticks = [];

%% Get summed patterns
% to do this, put a break point in Line 28 of
% \modules\pca\RunPCA\TiledPCA.m to get the Data variable, which is just
% the vectorized patterns. 
% vectorized patterns can be used straight for XCC study. Or you can use
% reshaped patterns to export to graphics.

sumpattern2 = sum(Data.Patterns_reshaped(:,z2),2);
% sumpattern2 = reshape(sumpattern2, [240 240]) ./ size(zz2,1);

sumpattern4 = sum(Data.Patterns_reshaped(:,z4),2);
% sumpattern4 = reshape(sumpattern4, [240 240]) ./ size(zz4,1);

sumpattern10 = sum(Data.Patterns_reshaped(:,z10),2);
% sumpattern10 = reshape(sumpattern5, [240 240]) ./ size(zz5,1);

sumPatterns = [sumpattern2 sumpattern4 sumpattern10];
numTemplates = size(sumPatterns,2);
%% Calculate XCF

XCFs = zeros(numTemplates, numPoints);

% you may choose to use the non-parallel version
parfor j=1:numPoints
thisPattern = Data.Patterns(:,j);

    for i=1:numTemplates
        thisTemplate = sumPatterns(:,i);
    XCFs(i,j) = max(normxcorr2(thisTemplate, thisPattern), [], "all");
    end

end

% XCC coefficients for each template
allXCFMaps = zeros(height, width, numTemplates);

for k=1:5
    thisMap = XCFs(k,:);
    thisMap = reshape(thisMap, [width height]);
    allXCFMaps(:,:,k) = thisMap;
    figure;
    imagesc(thisMap);  axis image; axis off;
    clim([0 0.8])
    colorbar;
    title(k)
    exportgraphics(gcf,sprintf('XCF_region_%s_nobar_noclim.png',num2str(k)),'Resolution',300);
end

% regions based on maximum XCC
[~,XCFMap] = max(allXCFMaps, [],1);

XCFMap = reshape(XCFMap, [height width]);
figure;
imagesc(XCFMap);  axis image; axis off;
colormap(cmapdouble);
cb=colorbar;
cb.TickLabels = [];
cb.Ticks = [];
